# ワークフロー名
name: LINE_Twitter_API

# ワークフロー実行タイミング
on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy
      - name: Run script
        run: |
          # favorites_text.pyの実行
          python favorites_text.py
